import "@/styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/Misc/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Readonly<Props>> = (props: Props) => {
  const { children } = props;

  return (
    <ClerkProvider>
      <html lang="en-gb">
        <body className="antialiased">
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
};

export default RootLayout;
