import "@/styles/globals.scss";
import type { Metadata } from "next";
import Header from "@/components/Misc/Header";
import { ToastContextProvider } from "@/contexts/ToastContext";
import GlobalContextProvider from "@/components/Misc/GlobalContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Readonly<Props>> = (props: Props) => {
  const { children } = props;

  return (
    <GlobalContextProvider>
      <html lang="en-gb">
        <body className="antialiased">
          <Header />

          <ToastContextProvider>{children}</ToastContextProvider>
        </body>
      </html>
    </GlobalContextProvider>
  );
};

export default RootLayout;
