import "@/styles/globals.scss";
import Header from "@/components/Misc/Header";
import Footer from "@/components/Misc/Footer";
import type { Metadata, Viewport } from "next";
import AppContextWrapper from "@/components/Misc/AppContextWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  // maximumScale: 5,
  // minimumScale: 1,
  // userScalable: true,
  viewportFit: "cover",
  width: "device-width",
  themeColor: "#222831",
};

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Readonly<Props>> = (props: Props) => {
  const { children } = props;

  return (
    <html lang="en-gb">
      <body className={`antialiased min-h-screen flex flex-col gap-0 justify-between items-stretch`}>
        <AppContextWrapper>
          <Header />
          {children}
          <Footer />
        </AppContextWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
